name: Publish Windows Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Windows Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="wintop-$tag-win-x64"
          echo "version=$(eval $tag)" >> $GITHUB_ENV
          # Build everything
          dotnet publish wintop.csproj --framework net5.0 --runtime "win-x64" -c Release -o "$release_name" --self-contained True -p:PublishSingleFile=True -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=True -p:TrimMode=Link -p:DebugType=None -p:DebugSymbols=False
          # Pack files
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
          # Delete output directory
          rm -r "$release_name"
      - name: Publish
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: "wintop-${{ env.version }}-win-x64.zip"